language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install setuptools>=26.0
  - pip install pytest==3.0.6
  - pip install coveralls pytest-cov
  - pip install https://github.com/darcymason/pydicom/archive/master.zip
  - pip install .
#  - pip install -r requirements.txt
# command to run tests
script: py.test --cov .
after_success:
  - coveralls